### ISSUE TITLE
Tube errors when invoked from guppy-setup.sh

### ISSUE THREAD

**Issue by michael-conway** [NIEHS/tube#1]
Attempting to run guppy setup to load a custom data model results in the following error:

```
Skipping table: _voided_edges
Skipping table: _voided_nodes
ERROR when running transformation
Traceback (most recent call last):
File "run_etl.py", line 31, in run_transform
translators = interpreter.create_translators(sc, config)
File "/tube/tube/etl/indexers/interpreter.py", line 10, in create_translators
dictionary, model = init_dictionary(config.DICTIONARY_URL)
File "/tube/tube/utils/dd.py", line 5, in init_dictionary
d = DataDictionary(url=url)
File "/usr/local/lib/python3.7/site-packages/dictionaryutils/__init__.py", line 168, in __init__
self.load_data(directory=self.root_dir, url=url, local_file=local_file)
File "/usr/local/lib/python3.7/site-packages/dictionaryutils/__init__.py", line 191, in load_data
for path, schema in yamls.items()
File "/usr/local/lib/python3.7/site-packages/dictionaryutils/__init__.py", line 192, in <dictcomp>
if path not in self.exclude
File "/usr/local/lib/python3.7/site-packages/dictionaryutils/__init__.py", line 237, in resolve_schema
return {k: self.resolve_schema(v, root) for k, v in obj.items()}
File "/usr/local/lib/python3.7/site-packages/dictionaryutils/__init__.py", line 237, in <dictcomp>
return {k: self.resolve_schema(v, root) for k, v in obj.items()}
File "/usr/local/lib/python3.7/site-packages/dictionaryutils/__init__.py", line 237, in resolve_schema
return {k: self.resolve_schema(v, root) for k, v in obj.items()}
File "/usr/local/lib/python3.7/site-packages/dictionaryutils/__init__.py", line 237, in <dictcomp>
return {k: self.resolve_schema(v, root) for k, v in obj.items()}
File "/usr/local/lib/python3.7/site-packages/dictionaryutils/__init__.py", line 236, in resolve_schema
obj.update(self.resolve_reference(val, root))
File "/usr/local/lib/python3.7/site-packages/dictionaryutils/__init__.py", line 210, in resolve_reference
resolver, new_root = self.resolvers[base]
KeyError: '_definitions.yaml'

guppy-service
guppy-service

```

the code in question in guppy-setup.sh is:

```
docker exec tube-service bash -c "python run_config.py && python run_etl.py"


```

the docker-compose file setting for tube was changed to:

```
    
DICTIONARY_URL=http://revproxy-service/api/v0/submission/getschema
```

which does return a valid JSON document reflecting our new schema. Smoketest for sheepdog and other services is nominal.

**Comment by michael-conway** [comment]
temporary code to load schema from file (after volume mount in docker-compose). This is in dictionaryutls __init__.py. A more formal method of patching this is still TBD

```
if not lazy:
            # self.load_data(directory=self.root_dir, url=url, local_file=local_file)
           self.load_data(directory=self.root_dir, url=None, local_file="/usr/share/gen3/custom/schema.json")




```
